# Generated by Django 4.2.5 on 2023-10-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0002_alter_user_email_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="password_predeterminada",
                max_length=128,
                verbose_name="password",
            ),
            preserve_default=False,
        ),
    ]
