# Generated by Django 4.2.5 on 2023-10-03 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0003_user_is_active_user_is_staff_user_last_login_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                ("machine_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("brand", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("format", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                ("shift_id", models.AutoField(primary_key=True, serialize=False)),
                ("shift_name", models.CharField(max_length=50)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ShiftAssignment",
            fields=[
                ("assignment_id", models.AutoField(primary_key=True, serialize=False)),
                ("assignment_date", models.DateField()),
                (
                    "machine_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="records.machine",
                    ),
                ),
                (
                    "shift_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="records.shift"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
