# Generated by Django 4.2.5 on 2023-10-03 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0004_machine_product_shift_shiftassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Production",
            fields=[
                ("prod_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.IntegerField()),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="records.product",
                    ),
                ),
                (
                    "shiftAssignment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="records.shiftassignment",
                    ),
                ),
            ],
        ),
    ]
