# Generated by Django 4.2.5 on 2023-10-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0005_user_is_superuser_production"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.IntegerField(
                choices=[
                    (0, "Machine worker"),
                    (1, "Warehouse worker"),
                    (2, "Supervisor"),
                    (3, "Manager"),
                    (4, "Admin"),
                ],
                default=0,
            ),
        ),
    ]
