# Generated by Django 4.2.7 on 2023-11-06 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_remove_shiftassignment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('storage_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('production_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.production')),
                ('storage_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
