# Generated by Django 4.2.5 on 2023-11-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0010_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="production",
            name="date_created",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="production",
            name="date_modified",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="production",
            name="time_created",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="production",
            name="time_modified",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
